Update guidelines Gitea
foss-ag/orga_guidelines pull request #18
Opened 2017-12-03 19:35 UTC by dragetd

Adjust guideles to resolve #15

2017-12-03 19:41 UTC, Lazalatin approved these changes
Finde ich so okay, könnte bei Zeiten aber nochmal verfeinert werden.

2017-12-04 21:25 UTC, Scosh commented
Find es auch erstmal gut so. Auch wenn ich es ja nicht mergen muss / approven muss, aber mein Senf ist jetzt gegeben. :P

2017-12-04 21:55 UTC, davidmehren requested changes
Siehe Kommentar.

2017-12-04 21:55 UTC, davidmehren commented on doc/guidelines_services.md
> +  - Jede Person kann auf Anfrage einen Account bekommen. Aktive Personen werden dort Member der FOSS-AG Organisation.
Bitte „aktive Mitglieder“ schreiben

2017-12-05 06:59 UTC, dragetd commented
Da ich den Fork bereits gelöscht habe, kann ich dies nicht mehr editieren. Ich werde Davids Änderung noch übernehmen, neuen PR machen und den dann mergen. Danke! :)

2017-12-05 06:59 UTC, closed without merging