Add infos and format of our meetings
foss-ag/orga_guidelines pull request #23
Opened 2018-02-15 21:01 UTC by dragetd

2018-02-16 11:12 UTC, fes0j reviewed
Unter dem Stichpunkt Allgemein sollte genauer stehen, was mit "Thema anfügen" gemeint ist. Ich wünsche mir eine Ergänzung in der Form "Wir benutzen ein geteiltes Dokument das allen zugänglich ist. Darauf werden die Themen eingetragen. Während der Sitzung wird in daraus dann ein Protokoll."

Bei den Hackgruppen sollte vielleicht expliziter stehen, dass mehrere parallel stattfinden können.

2018-02-20 19:26 UTC, Lazalatin commented
Habe einfach mal ein paar kleinere Schreibfehler korrigiert.
Bin sonst zufrieden.

2018-02-20 19:28 UTC, dragetd commented
Vorschlag von Innay:

Kurzvorstellungen zu Themen die man evtl. in einer kleineren Runde besprechen will auch dann ohne viele Kommentare und am Anfang des Stammtisches, dann mit dem Verweis auf Hackgruppen/Diskussionsrunden am Ende

2018-02-20 20:24 UTC, davidmehren requested changes
Bisschen Tippfehler und ein inhaltlicher Kommentar.

2018-02-20 20:24 UTC, davidmehren commented on doc/meetings.md
> +  - Stammtisch (Vorstellung neuer und cooler Projekte/-ideen zu FOSS-Themen. Bevorzugt kleine Vorträge evtl. mit Folien. Alternativ, wenn man sich selbst damit nicht beschätigt hat, nur eine kurze Vo
`beschätigt` -> `beschäftigt`

2018-02-20 20:24 UTC, davidmehren commented on doc/meetings.md
> +  - Stammtisch (Vorstellung neuer und cooler Projekte/-ideen zu FOSS-Themen. Bevorzugt kleine Vorträge evtl. mit Folien. Alternativ, wenn man sich selbst damit nicht beschätigt hat, nur eine kurze Vo
Würde ggf. den Nebensatz "wenn man sich selbst damit nicht beschätigt hat" komplett streichen. Ich kann mich ja auch mit was beschäftigt haben und dazu eine Hackgruppe haben wollen.

2018-02-20 20:24 UTC, davidmehren commented on doc/meetings.md
> +  - Hackgruppen (Gemeinsames beschäftigen mit bestehenden/neuen Projekten (z.B. die im Stammtisch vorgestellt wurden) in kleineren Gruppen)
`beschäftigen` -> `Beschäftigen`

2018-02-21 19:45 UTC, InnayTool commented on doc/meetings.md
> +  - Hackgruppen (Gemeinsames beschäftigen mit bestehenden/neuen Projekten (z.B. die im Stammtisch vorgestellt wurden) in kleineren Gruppen)
Also ich finde wir müssen dafür jetzt eigentlich nicht einen neuen Begriff einführen, sondern können sowas sagen wie: "mit Verweis auf eine der FOSS-AG Sitzung nachgestellte Disskussion".
Ich finde mehr Namen für Dinge führen unter Umständen eher zu mehr Verwirrung und es ist vermutlich für neue Menschen einfacher zu verstehen, wenn man es einfach Ausspricht was man meint.
Und ich sehe den Mehrwert eines neuen Wortes dafür noch nicht wirklich.

2018-02-21 20:01 UTC, dragetd commented on doc/meetings.md
> +  - Hackgruppen (Gemeinsames beschäftigen mit bestehenden/neuen Projekten (z.B. die im Stammtisch vorgestellt wurden) in kleineren Gruppen)
I agree. Lass uns den extra Namen streichen und einfach von Diskussionsgruppen reden. :)

2018-02-21 20:54 UTC, InnayTool commented
Ich glaube das ist noch zu unklar, wann diese Disskussionen sein sollen.

2018-02-21 23:31 UTC, Lazalatin requested changes
Correction

2018-02-21 23:31 UTC, Lazalatin commented on doc/meetings.md
> +    - Zunächst kurze Vorstellung von Projekten über die es anschließsenden Diskussionsgruppen gibt
[...] über die es "anschließende" Diskussionsgruppen gibt

2018-02-21 23:32 UTC, Lazalatin commented
Ich würde gerne den Passus wieder herstellen, welcher den Kurzvortrag als bevorzugtes Medium hervorhebt... Wie sind da die Meinungen?

2018-02-22 15:31 UTC, Lazalatin approved these changes

2018-02-22 15:32 UTC, Lazalatin commented on doc/meetings.md
> +    - Zunächst kurze Vorstellung von Projekten über die es anschließsenden Diskussionsgruppen gibt
Wer write access hat sollte Gebrauch von der Commenting-Funktion machen :P

2018-02-22 15:43 UTC, fes0j approved these changes
Rechtschreibkorrektur immer gut. Inhaltliche Spezifizierungen am Besten mit neuen PR's.

2018-02-22 15:58 UTC, Lazalatin commented
> Rechtschreibkorrektur immer gut. Inhaltliche Spezifizierungen am Besten mit neuen PR's.

Finde ich gut :)

2018-02-22 19:05 UTC, merged