Entfernung der 'Aktiven' Rolle.
foss-ag/orga_guidelines pull request #33
Opened 2018-05-24 20:03 UTC by dragetd

Stattdessen gibt es Stimmberechtigte und einen neuen, öffentlichen Organisationskanal.

Übernimmt die Vorschläge von Thief und Chef aus #31 und #32 bezüglich der Änderung (bzw. letztendlich Entfernung) der 'Aktiven' Rolle und übernimmt das Kanal-Layout von Draget aus #31.

2018-05-28 07:22 UTC, ROYALBEFF approved these changes

2018-05-28 08:20 UTC, dragetd commented
Auch wenn ich die Kanal-Phobie (;-P *drück*) von Laz nicht ganz nachvollziehen kann , so habe ich nichts gegen die Änderung.

Ein 'Organisations Kanal', ein Chat-kanal. Soll mir recht sein. Da der aktuelle Orga-Kanal allerdings in der History Links, Bilder und Co. enthält die mal gepostet wurden unter dem Glauben der Kanal sei nicht öffentlich im Netz indexierbar, würde ich dann einen neuen Kanal machen.

2018-05-29 09:40 UTC, dragetd commented
Wenn ihr mit den Änderungen einverstanden sein, könnt ihr den PR 'approven'. Jeder aus der FOSS-AG. Das Feedback wäre nicht schlecht! Oder wenn ihr es doof findet, dann auch dieses Feedback! :)

2018-05-29 12:44 UTC, dragetd commented
Was haltet ihr von den 'Stimmberechtigten' - das können wir von mir aus auch raus nehme, falls jemand damit Bauchschmerzen hat.

2018-05-29 15:08 UTC, davidmehren commented
Ich finde das jetzt nicht sooo unglaublich sinnvoll, weil im Endeffekt ersetzen wir das "aktive Mitglied" durch "jeder, mit Vetovorbehalt durch Stimmberechtigte". Da es für die Stimmberechtigung auch ein Vetorecht gibt, ändert sich effektiv nichts, außer das die Formulierung an mehreren Stellen intransparenter wird.

Hier wird auch die Umbenennung der aktiven Mitglieder mit der Öffentlichmachung des Orgakanals vermischt, was für die Trennung der Diskussion nicht soo optimal ist.
Ich fänd eine Trennung in aktive Mitglieder, Kanalstruktur und Dienstberechtigungen sinnvoll.

2018-05-29 16:28 UTC, dragetd commented
- Ja, im Prinzip wird die Rolle der 'Aktiven' umbenannt. Der Name war doof, weil 'aktiv' sind wir alle. Wir wollten das damals um bei Abstimmungen eine Reglung bezüglich Gästen und Neulingen zu haben. Deswegen ist der Name 'Stimmberechtigt' passender, so die Idee von @ROYALBEFF und mir.

Einher geht damit, dass die ex-'Aktiven'-Rolle, jetzt 'Stimmberechtigter'-Rolle keine weiteren Rechte mit sich bringt, weder bei Diensten noch Räumen.
- Die Verknüpfung mit den Dienstrechten ist ebenfalls entfernt.


Ich könnte dies in zwei PRs aufteilen:
1) Entfernung der Aktiven Rolle, einführung der Stimmberechtigten Rolle und Trennung der Dienst-Rechte von den Rollen
2) Neue Matrix-Räume.

Ist halt etwas aufwendiger, weil die PRs die selben Dinge ändern und dann gemerged werden müssen. Wenn außer dir noch jemand sagt 'Ja, das sollten zwei RPs sein', dann bitte diesen PR ablehnen (sollten alle FOSS-AGler können), dann mache ich zwei neue! :)

PS: Sollten die oben Beschriebenen Dinge aus dem neuen Text (nach dem PR) nicht hervor gehen, dann bitte ich um Kommentare an welcher Stelle es zu Verständnisproblemen kommt)

2018-05-29 17:18 UTC, Lazalatin commented
Da zu den beiden Diskussionen zwei separierte Issues existieren, finde ich das soweit okay :) Der PR kann mEn bleiben ;)

2018-06-04 11:19 UTC, davidmehren commented
@Lazalatin @InnayTool @Scosh und Arne hatten da letzten Donnerstag drüber diskutiert.
Auch wenn ich grade nicht mehr alle Ergebnisse zusammenkriege, so war doch zumindest Konsens bei uns, dass man die Diskussion und damit diesen PR in die Teile „Bezeichnung aktive Mitglieder“, „Dienstrechte“ und „Matrix-Räume“ teilen sollte. Die sind schließlich unabhängig voneinander diskutier- und implementierbar.

2018-06-04 11:19 UTC, davidmehren requested changes
Wie bereits kommentiert, bitte in mehrere PRs aufspalten.

2018-06-04 18:49 UTC, ThiefOfTime approved these changes
ich bin mir noch nicht sicher, wie wir das mit den Stimmberechtigten machen und sehe da das Problem des sich schließenden Kreises, aber ist ja nicht gegenstand dieses PRs und somit noch Zukunftsmusik

2018-06-04 21:14 UTC, Lazalatin commented
@davidmehren würdest du den PR akzeptieren, wenn wir ihn wie jetzt mergen? Ich denke dass wir mit den Diskussionen soweit ohnehin am Ende sind.

2018-06-04 21:14 UTC, Lazalatin approved these changes

2018-06-05 08:37 UTC, dragetd commented
(Mir ist bewusst, dass wir es hier etwas umständlicher machen als Nötig. Aber ich finde es macht auch Spaß, Dinge ordentlich zu planen. :) )

Deswegen schließe ich diesen PR und mache zwei neue auf bei denen ich versuche, die beiden Aspekte voneinander zu trennen!

2018-06-05 08:37 UTC, closed without merging